---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyPage/index.html
    destin_file: /var/www/html
  
  tasks:
  - name: Install Apache Web Server
    yum: name=httpd state=latest

  - name: Copy MyPage to Server
    copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Server and make it enable on boot
    service: name=httpd  state=started  enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted