---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyPage/index.html
    destin_file: /var/www/html

  tasks:
  - name: Check and Print OS Family
    debug: var="ansible_os_family"

  - block:      ## ======Block for RedHat======
      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: Copy MyPage to Server
        copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
        notify: Restart Apache RedHat

      - name: Start Web Server and make it enable on boot
        service: name=httpd  state=started  enabled=yes
    when: ansible_os_family == "RedHat"

  - block:      ## ======Block for Debian======
      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Copy MyPage to Server
        copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
        notify: Restart Apache Debian

      - name: Start Web Server and make it enable on boot
        service: name=apache2  state=started  enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
