---
- name: My Awesome Playbook
  hosts: all
  become: yes

  vars:
   mytext: "Hello World"

  tasks:
  - name: Ping test
    ping:

  - name: Create file1
    copy:
      dest: /home/toserver/file1.txt
      content: |
        this is file1
        fixed message: Hello World
        my    message: {{ mytext }}

  - name: Create ffile2
    copy:
      dest: /home/toserver/file2.txt
      content: |
        this is file2
        fixed message: Hello World
        my    message: {{ mytext }}