---
- name: My Awesome Playbook for Variables
  hosts: all
  become: yes

  vars:
    message1 : Hello
    message2 : World
    secret   : QWRTGHJGERYUUJGJ

  tasks:
  - name: Print Secret Variable
    debug:
      var: secret

  - debug:
      msg: "Secret word is: {{ secret }}"

  - debug:
      msg: "Owner of this server is: -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - debug:
      var: ansible_os_family

  - shell: uptime
    register: results

  - debug:
      var: results.stdout
