---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_folder: ./MyPage2
    destin_folder: /var/www/html

  tasks:
  - name: Check and Print OS Family
    debug: var="ansible_os_family"

  - block:      ## ======Block for RedHat======
      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest
      - name: Start Web Server and make it enable on boot
        service: name=httpd  state=started  enabled=yes
    when: ansible_os_family == "RedHat"

  - block:      ## ======Block for Debian======
      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest
      - name: Start Web Server and make it enable on boot
        service: name=apache2  state=started  enabled=yes
    when: ansible_os_family == "Debian"

  - name: Generate index.html file
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder}} mode=0555
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian

  - name: Copy MyPage2 to Server
    copy: src={{ source_folder }}/{{ item }}  dest={{ destin_folder }} mode=0555
#    with_fileglob: "{{ source_folder }}/*.*" #alt loop method
    loop:
#      - "index.html"
      - "pic1.png"
      - "pic2.png"
      - "pic3.png"
      - "pic4.png"
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
