---
- name: My Awesome Playbook for Variables
  hosts: all
  become: yes

  vars:
    message1 : Hello
    message2 : World
    secret   : QWRTGHJGERYUUJGJ

  tasks:
  - name: Print Secret Variable
    debug:
      var: secret

    debug:
      msg: "Secret word is: {{ secret }}"