---
- name: My Awesome Playbook
  hosts: all
  become: yes

  vars:
   mytext: "Hello World"

  tasks:
  - name: Ping test
    ping:

  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml mytest="World Hello"

#  - name: import code here
#    import: import_this.yml