---
- name: Ansible vault
  hosts: all
  become: yes

  vars:
    admin_password: V3ryS3cr3t

  tasks:
  - name: Create config file
    copy:
      dest: "/home/ec2-user/myconfig.conf"
      content: |
        port = 9999
        log  = 7days
        home = /opt/kafka/bin/
        user = admin
        password= {{ admin_password }}