---
- name: Error handling
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: Task no 1
    yum: name=treeeee state=latest
    ignore_errors: yes

  - name: Task no 2
    shell: cat /home/ec2-user/myfile.txt
    register: results
#    failed_when: results.rc == 0
#    failed_when: "'World' in results.stdout"

  - debug:
      var: results

  - name: Task no 3
    shell: Privet Mir