---
- name: Error handling
  hosts: all
  become: yes

  tasks:
  - name: Task no 1
    yum: name=treeeee state=latest
    ignore_errors: yes

  - name: Task no 2
    shell: ls -la /etc/
    register: results

  - debug:
      var: results

  - name: Task no 3
    shell: Privet Mir