---
- name: Install Apache and Upload my Web Page
  #hosts: all
  hosts: "{{ MYHOSTS }}"
  #ansible-playbook playbook9roles.yml --extara-var "MYHOSTS=LINUX"
  become: yes

  roles:
    - { role: deploy_apache_web, when: ansible_os_family == 'Linux' }
# deploy db
